
# C Audit developer targets.
#
# `make check` is the single quality gate. CI invokes exactly this target, so
# a local pass and a CI pass cannot diverge (AC-01-7).

PYTHON ?= python3
VENV   ?= .venv
BIN    := $(VENV)/bin

.DEFAULT_GOAL := help
.PHONY: help bootstrap lint typecheck test check guard schemas schema-check docs-check \
        architecture-check record-baseline doctor eval eval-real clean

# Paths that are generated output, independent upstream clones, or a local
# secret, and so must never be tracked. Kept in sync with .gitignore and the
# pre-commit hooks of the same name; `make guard` is the copy CI actually runs.
# `^\.env$$` matches the bare file only, so the committed `.env.example`
# template is unaffected -- grep -E has no negative lookahead to express an
# exception with, so the pattern is written not to need one.
UNTRACKABLE := (^|/)__pycache__/|\.py[cod]$$|^\.coverage|^caudit-(report|eval|pairs|ablation|calibration)/|^\.(pytest|mypy|ruff)_cache/|^\.hypothesis/|^htmlcov/|^inspiration_repos/|^audit-targets/|^\.env$$

# What `make clean` deletes: every generated path UNTRACKABLE names, minus the
# durable paths it must not touch. `inspiration_repos/` contains read-only
# reference clones, while `audit-targets/` contains user-controlled repositories
# being scanned. Both have their own upstream remotes, and neither is generated
# by C Audit. `.env` is excluded for a stronger reason: it holds an API key, so
# it cannot be regenerated by any later run at any price. `.venv/` is not in
# UNTRACKABLE at all and belongs to `bootstrap`.
# Everything below is rebuilt by whichever run needs it next, so removing it
# costs time and nothing else. T-01-16 asserts this list against UNTRACKABLE:
# the two are one decision spelled twice, and nothing else notices them drift.
GENERATED := .pytest_cache .mypy_cache .ruff_cache .hypothesis .coverage .coverage.* \
             htmlcov caudit-report caudit-eval caudit-pairs caudit-ablation \
             caudit-calibration build dist *.egg-info src/*.egg-info

help: ## Show this help
	@grep -hE '^[a-zA-Z_-]+:.*?## ' $(MAKEFILE_LIST) \
		| awk 'BEGIN {FS = ":.*?## "}; {printf "  \033[36m%-16s\033[0m %s\n", $$1, $$2}'

bootstrap: ## Create the virtualenv and install everything
	$(PYTHON) -m venv $(VENV)
	$(BIN)/python -m pip install --upgrade pip
	$(BIN)/pip install -e '.[dev]'
	@echo
	@echo "Next: make doctor  (reports any missing LLVM components)"

lint: ## ruff
	$(BIN)/ruff check src tests tools
	$(BIN)/ruff format --check src tests tools

typecheck: ## mypy --strict
	$(BIN)/mypy

test: ## pytest with the coverage floor
	$(BIN)/pytest --cov --cov-report=term-missing

guard: ## Fail if generated output, a nested repository, or .env is tracked
	@bad=$$(git ls-files | grep -E '$(UNTRACKABLE)' || true); \
	if [ -n "$$bad" ]; then \
		n=$$(printf '%s\n' "$$bad" | wc -l); \
		echo "$$n tracked path(s) are generated output, a nested repository, or a secret:"; \
		printf '%s\n' "$$bad" | head -10 | sed 's/^/    /'; \
		[ "$$n" -gt 10 ] && echo "    ... and $$((n - 10)) more"; \
		echo "Untrack them (the files stay on disk):"; \
		echo "    git rm -r --cached <path>"; \
		exit 1; \
	fi

check: guard lint typecheck schema-check docs-check architecture-check test ## Everything CI runs

schemas: ## Regenerate the committed JSON Schemas
	$(BIN)/python tools/export_schemas.py

schema-check: ## Fail if a model changed without a schema export
	$(BIN)/python tools/export_schemas.py --check

docs-check: ## Verify canonical docs and internal Markdown links
	$(BIN)/python tools/check_docs.py

architecture-check: ## Enforce import-layer contracts
	$(BIN)/lint-imports

record-baseline: ## Capture real analyzer output for benchmarks/mini (needs Clang)
	$(BIN)/python tools/record_baseline.py

doctor: ## Report toolchain status
	$(BIN)/caudit doctor

# Replays the committed recordings, so it needs no LLVM and is what CI runs.
# A number from here is a replay of what the analyzers said when they were
# recorded; use `eval-real` for anything that gets published.
eval: ## Score the mini suite with analyzers only, from recordings
	$(BIN)/caudit eval --suite mini --baseline --recorded --out caudit-eval

eval-real: ## Score the mini suite by running the real analyzers (needs Clang)
	$(BIN)/caudit eval --suite mini --baseline --use-clang --out caudit-eval

clean: ## Remove generated output (keeps .venv and nested repositories)
	rm -rf $(GENERATED)
	find . -path ./.venv -prune -o -path ./inspiration_repos -prune -o -path ./audit-targets -prune -o \
	       -name '__pycache__' -type d -prune -exec rm -rf {} +
	find . -path ./.venv -prune -o -path ./inspiration_repos -prune -o -path ./audit-targets -prune -o \
	       -name '*.py[cod]' -type f -exec rm -f {} +
