"""Blind spots, as data.

Every fact this part cannot establish becomes a typed
:class:`~caudit.model.finding.Limitation` rather than a default, a guess, or a
silence. The builders live together so the wording of each blind spot is
written once: a reader who sees ``parse_failed`` twice in a report should be
able to compare the two lines without parsing two different phrasings.

One rule holds across all of them (AC-06-11): **every limitation names a
file**, and names the symbol too whenever the blind spot is attached to one.
``affects`` is therefore mandatory here, unlike in the model, and
:func:`describe_target` is the single place that formats it.
"""

from __future__ import annotations

from collections.abc import Iterable
from pathlib import PurePosixPath

from caudit.model.finding import Limitation, LimitationKind

__all__ = [
    "LimitationLog",
    "ambiguous_virtual_dispatch",
    "describe_target",
    "inline_assembly",
    "macro_expansion_unavailable",
    "missing_header",
    "parse_failed",
    "parse_timed_out",
    "toolchain_headers_unavailable",
    "unresolved_indirect_call",
]

#: Printed whenever a parse fails on Clang's own builtin headers. The wheel
#: ships ``libclang.so`` and nothing else, so this is the single most likely
#: first-run failure on a real repository.
RESOURCE_DIR_HINT = (
    "the libclang wheel ships no builtin headers; supply Clang's resource "
    'directory with --set index.resource_dir="$(clang -print-resource-dir)"'
)


def describe_target(path: PurePosixPath | str, symbol: str | None = None) -> str:
    """``src/parse.c`` or ``src/parse.c::parse_header`` — the ``affects`` form."""
    return f"{path}::{symbol}" if symbol else str(path)


def parse_failed(path: PurePosixPath | str, first_error: str) -> Limitation:
    """A translation unit Clang could not parse. It is excluded, not ignored."""
    return Limitation(
        kind=LimitationKind.PARSE_FAILED,
        detail=(
            f"{path} did not parse and is not in the index; no finding can be "
            f"reported in it. First error: {first_error}"
        ),
        affects=describe_target(path),
    )


def missing_header(path: PurePosixPath | str, header: str, *, builtin: bool) -> Limitation:
    """A header Clang could not find. Names the header, not just the TU."""
    reason = (
        f"{RESOURCE_DIR_HINT}. "
        if builtin
        else "it is generated by the build, or an include path is missing from the "
        "compilation database. "
    )
    return Limitation(
        kind=LimitationKind.PARSE_FAILED,
        detail=(
            f"{path} includes {header!r}, which Clang could not find, so the "
            f"translation unit is not in the index — {reason}"
            "C Audit does not invent include paths"
        ),
        affects=describe_target(path),
    )


def parse_timed_out(path: PurePosixPath | str, seconds: float) -> Limitation:
    """A parse that ran past its ceiling. A skip that says so."""
    return Limitation(
        kind=LimitationKind.PARSE_FAILED,
        detail=(
            f"{path} was still parsing after {seconds:g}s and was stopped; it is not "
            "in the index. Raise index.per_tu_timeout_seconds if the file is "
            "genuinely that large"
        ),
        affects=describe_target(path),
    )


def unresolved_indirect_call(
    path: PurePosixPath | str, line: int, symbol: str | None, spelling: str | None
) -> Limitation:
    """An indirect call. The edge exists; only its target is unknown."""
    through = f" through {spelling}" if spelling else ""
    return Limitation(
        kind=LimitationKind.UNRESOLVED_INDIRECT_CALL,
        detail=(
            f"{path}:{line} calls{through} a function pointer whose target is not "
            "known statically; the call graph records the edge with an unknown "
            "callee, so a caller set that includes this site is a lower bound"
        ),
        affects=describe_target(path, symbol),
    )


def ambiguous_virtual_dispatch(
    path: PurePosixPath | str, line: int, symbol: str | None, method: str, overrides: int
) -> Limitation:
    """Virtual dispatch: edges to every override we saw, which may not be all."""
    return Limitation(
        kind=LimitationKind.UNRESOLVED_INDIRECT_CALL,
        detail=(
            f"{path}:{line} dispatches virtually to {method}; edges were recorded to "
            f"the {overrides} override(s) visible in the parsed translation units, and "
            "an override in a TU that was not parsed would be missing from that set"
        ),
        affects=describe_target(path, symbol),
    )


def inline_assembly(path: PurePosixPath | str, line: int, symbol: str | None) -> Limitation:
    """Inline asm: the analysis stops at the boundary of what Clang models."""
    return Limitation(
        kind=LimitationKind.INLINE_ASSEMBLY,
        detail=(
            f"{path}:{line} contains inline assembly, which is opaque to the index; "
            "memory it reads or writes is invisible to any claim made about this "
            "function"
        ),
        affects=describe_target(path, symbol),
    )


def macro_expansion_unavailable(path: PurePosixPath | str, name: str) -> Limitation:
    """A macro used here, defined somewhere we cannot cite."""
    return Limitation(
        kind=LimitationKind.MACRO_EXPANSION_UNAVAILABLE,
        detail=(
            f"{path} expands the macro {name}, whose definition is outside the "
            "repository; the expansion site is citable but the definition is not"
        ),
        affects=describe_target(path),
    )


def toolchain_headers_unavailable(path: PurePosixPath | str) -> Limitation:
    """The resource-directory blind spot, stated once per affected TU."""
    return Limitation(
        kind=LimitationKind.TOOLCHAIN_UNAVAILABLE,
        detail=f"{path} could not be parsed because {RESOURCE_DIR_HINT}",
        affects=describe_target(path),
    )


class LimitationLog:
    """Insertion-ordered, deduplicated limitations.

    Ordering is by (kind, affects, detail) at read time rather than by arrival,
    so two runs that discover the same blind spots in a different order still
    serialize identically.
    """

    def __init__(self, limitations: Iterable[Limitation] = ()) -> None:
        self._seen: dict[tuple[str, str, str], Limitation] = {}
        self.extend(limitations)

    def add(self, limitation: Limitation) -> None:
        self._seen.setdefault(self._key(limitation), limitation)

    def extend(self, limitations: Iterable[Limitation]) -> None:
        for limitation in limitations:
            self.add(limitation)

    @staticmethod
    def _key(limitation: Limitation) -> tuple[str, str, str]:
        return (str(limitation.kind), limitation.affects or "", limitation.detail)

    def all(self) -> list[Limitation]:
        return [self._seen[key] for key in sorted(self._seen)]

    def of_kind(self, kind: LimitationKind) -> list[Limitation]:
        return [item for item in self.all() if item.kind is kind]

    def kinds(self) -> set[str]:
        return {str(item.kind) for item in self.all()}

    def __len__(self) -> int:
        return len(self._seen)
