"""Part 05 filtering tests: T-05-11 … T-05-14.

Exclusions are the quietest way a scan can mislead: a file nobody looked at
produces no findings, which reads exactly like a file with no bugs. Each test
here asserts both halves — that the right thing was excluded, and that the
plan says so.
"""

from __future__ import annotations

from pathlib import Path, PurePosixPath

import pytest

from caudit.errors import IntakeError
from caudit.intake import load_scan_plan
from caudit.intake.filters import (
    ExclusionRules,
    TargetSelector,
    has_generated_banner,
    is_generated_name,
    is_third_party_path,
)
from caudit.intake.plan import ExclusionReason
from caudit.status import ExitCode
from tests.conftest import compdb_entry, intake_config, write_compdb, write_tree

BANNER = "/* Generated by protoc.  DO NOT EDIT. */\n"


def _five_entry_repo(tmp_path: Path) -> tuple[Path, Path]:
    root = write_tree(
        tmp_path,
        {f"src/{name}.c": f"void {name}(void) {{}}\n" for name in ("a", "b", "c", "d", "e")},
    )
    database = write_compdb(
        root, [compdb_entry(root, str(root / f"src/{n}.c")) for n in ("a", "b", "c", "d", "e")]
    )
    return root, database


def test_target_with_no_matching_entry_stops_and_suggests(tmp_path: Path) -> None:
    """T-05-11: a target that matches nothing is a typo, not an empty scan."""
    root, database = _five_entry_repo(tmp_path)
    with pytest.raises(IntakeError) as excinfo:
        load_scan_plan(root, database, intake_config(targets=["src/missing.c"]))
    assert excinfo.value.exit_code is ExitCode.ENVIRONMENT
    assert "src/missing.c" in excinfo.value.message
    hint = excinfo.value.hint or ""
    assert "nearest entries" in hint
    suggested = hint.split("nearest entries: ")[1].splitlines()[0].split(", ")
    assert suggested, "the stop must name something the database actually contains"
    assert set(suggested) <= {f"src/{name}.c" for name in "abcde"}
    assert "The database describes 5 file(s)" in hint


def test_target_narrows_the_plan_and_names_the_rest(tmp_path: Path) -> None:
    """T-05-12: 1 selected, 4 recorded as `not_selected` — not silently gone."""
    root, database = _five_entry_repo(tmp_path)
    plan = load_scan_plan(root, database, intake_config(targets=["src/a.c"]))

    assert [unit.file for unit in plan.units] == [PurePosixPath("src/a.c")]
    assert plan.coverage.tus_selected == 1
    assert plan.coverage.tus_excluded[ExclusionReason.NOT_SELECTED] == 4
    assert len(plan.excluded_by(ExclusionReason.NOT_SELECTED)) == 4
    # Narrowing the scan must not make the build description look incomplete.
    assert plan.coverage.coverage_ratio == 1.0


def test_a_target_may_name_a_directory(tmp_path: Path) -> None:
    root = write_tree(tmp_path, {"src/a.c": "void a(void){}\n", "tools/t.c": "void t(void){}\n"})
    database = write_compdb(
        root,
        [compdb_entry(root, str(root / "src/a.c")), compdb_entry(root, str(root / "tools/t.c"))],
    )
    plan = load_scan_plan(root, database, intake_config(targets=["src"]))
    assert [unit.file for unit in plan.units] == [PurePosixPath("src/a.c")]


def test_default_exclusions_attribute_the_right_reason(tmp_path: Path) -> None:
    """T-05-13: vendored, moc, protobuf, and banner files, each named."""
    root = write_tree(
        tmp_path,
        {
            "src/real.c": "void real(void){}\n",
            "third_party/dep.c": "void dep(void){}\n",
            "src/moc_widget.cpp": "void moc(void){}\n",
            "src/message.pb.cc": "void pb(void){}\n",
            "src/banner.c": BANNER + "void banner(void){}\n",
        },
    )
    database = write_compdb(
        root,
        [
            compdb_entry(root, str(root / relative))
            for relative in (
                "src/real.c",
                "third_party/dep.c",
                "src/moc_widget.cpp",
                "src/message.pb.cc",
                "src/banner.c",
            )
        ],
    )
    plan = load_scan_plan(root, database, intake_config())

    assert [unit.file for unit in plan.units] == [PurePosixPath("src/real.c")]
    attributed = {str(path): reason for path, reason in plan.excluded}
    assert attributed == {
        "third_party/dep.c": ExclusionReason.THIRD_PARTY,
        "src/moc_widget.cpp": ExclusionReason.GENERATED,
        "src/message.pb.cc": ExclusionReason.GENERATED,
        "src/banner.c": ExclusionReason.GENERATED,
    }
    # The excluded files are out of the denominator too: a repository that
    # vendors code is not thereby an incompletely described one.
    assert plan.coverage.source_files_in_tree == 1
    assert plan.coverage.coverage_ratio == 1.0


def test_generated_inside_third_party_is_reported_as_generated(tmp_path: Path) -> None:
    """The more actionable of two true reasons wins, by a documented order."""
    root = write_tree(tmp_path, {"third_party/x.pb.cc": "void x(void){}\n"})
    database = write_compdb(root, [compdb_entry(root, str(root / "third_party/x.pb.cc"))])
    plan = load_scan_plan(root, database, intake_config())
    assert plan.excluded == [(PurePosixPath("third_party/x.pb.cc"), ExclusionReason.GENERATED)]


def test_vendored_code_with_an_explicit_opt_in_is_scanned_and_disclosed(
    tmp_path: Path,
) -> None:
    """T-05-14: opting in works, and the plan records that it happened."""
    root = write_tree(
        tmp_path,
        {"src/real.c": "void real(void){}\n", "third_party/dep.c": "void dep(void){}\n"},
    )
    database = write_compdb(
        root,
        [
            compdb_entry(root, str(root / "src/real.c")),
            compdb_entry(root, str(root / "third_party/dep.c")),
        ],
    )

    default = load_scan_plan(root, database, intake_config())
    assert default.excluded_by(ExclusionReason.THIRD_PARTY) == [PurePosixPath("third_party/dep.c")]
    assert default.overrides == []

    opted_in = load_scan_plan(root, database, intake_config(include_third_party=True))
    assert [unit.file for unit in opted_in.units] == [
        PurePosixPath("src/real.c"),
        PurePosixPath("third_party/dep.c"),
    ]
    assert opted_in.excluded == []
    assert opted_in.overrides == ["intake.include_third_party"]


def test_targeting_a_vendored_file_does_not_silently_include_it(tmp_path: Path) -> None:
    """Naming a path is not the opt-in. Widening scope must stay explicit.

    The user still learns what happened: the file is listed as excluded with
    its reason, rather than the scan quietly finding nothing.
    """
    root = write_tree(tmp_path, {"third_party/dep.c": "void dep(void){}\n"})
    database = write_compdb(root, [compdb_entry(root, str(root / "third_party/dep.c"))])

    plan = load_scan_plan(root, database, intake_config(targets=["third_party/dep.c"]))
    assert plan.units == []
    assert plan.excluded == [(PurePosixPath("third_party/dep.c"), ExclusionReason.THIRD_PARTY)]

    opted_in = load_scan_plan(
        root, database, intake_config(targets=["third_party/dep.c"], include_third_party=True)
    )
    assert [unit.file for unit in opted_in.units] == [PurePosixPath("third_party/dep.c")]


def test_generated_code_opt_in_is_separate_from_the_vendoring_one(tmp_path: Path) -> None:
    root = write_tree(tmp_path, {"src/banner.c": BANNER + "void banner(void){}\n"})
    database = write_compdb(root, [compdb_entry(root, str(root / "src/banner.c"))])
    plan = load_scan_plan(root, database, intake_config(include_generated=True))
    assert [unit.file for unit in plan.units] == [PurePosixPath("src/banner.c")]
    assert plan.overrides == ["intake.include_generated"]


@pytest.mark.parametrize(
    "path",
    ["third_party/a.c", "libs/vendor/b.c", "external/c.c", "x/node_modules/d.c", "build/e.c"],
)
def test_vendoring_directories_match_at_any_depth(path: str) -> None:
    assert is_third_party_path(path)


@pytest.mark.parametrize("path", ["src/a.c", "vendored_things.c", "my_external_api.c"])
def test_similar_names_are_not_vendoring_directories(path: str) -> None:
    """Segment matching, not substring matching — `my_external_api.c` is ours."""
    assert not is_third_party_path(path)


@pytest.mark.parametrize(
    "name",
    ["a.pb.cc", "a.pb.h", "moc_widget.cpp", "ui_form.h", "thing_generated.cpp", "lex.yy.c"],
)
def test_generator_naming_conventions(name: str) -> None:
    assert is_generated_name(f"src/{name}")


@pytest.mark.parametrize(
    "first_line",
    [
        "// @generated",
        "/* DO NOT EDIT - this file is generated by flex */",
        "# Automatically generated by configure",
        " * This file was auto-generated.",
        "// machine generated, do not modify",
    ],
)
def test_generated_banners_are_recognized(tmp_path: Path, first_line: str) -> None:
    source = tmp_path / "x.c"
    source.write_text(f"{first_line}\nvoid x(void){{}}\n", encoding="utf-8")
    assert has_generated_banner(source)


def test_a_banner_in_code_rather_than_a_comment_is_not_a_banner(tmp_path: Path) -> None:
    """The documented false-positive risk, held to comment lines only."""
    source = tmp_path / "x.c"
    source.write_text(
        'const char *warning = "DO NOT EDIT this configuration by hand";\nvoid x(void){}\n',
        encoding="utf-8",
    )
    assert not has_generated_banner(source)


def test_a_banner_below_the_scanned_window_is_not_a_banner(tmp_path: Path) -> None:
    source = tmp_path / "x.c"
    source.write_text("\n" * 8 + "// generated by protoc\n", encoding="utf-8")
    assert not has_generated_banner(source)


def test_an_unreadable_file_is_not_assumed_generated(tmp_path: Path) -> None:
    assert not has_generated_banner(tmp_path / "does-not-exist.c")


def test_undecodable_bytes_do_not_crash_banner_detection(tmp_path: Path) -> None:
    source = tmp_path / "x.c"
    source.write_bytes(b"// generated by \xff\xfe protoc\nvoid x(void){}\n")
    assert has_generated_banner(source)


def test_the_selector_is_inert_when_no_target_was_given() -> None:
    selector = TargetSelector()
    assert not selector.active
    assert selector.selects(PurePosixPath("anything/at/all.c"))
    assert selector.unmatched([PurePosixPath("src/a.c")]) == []


def test_exclusion_order_puts_target_narrowing_first(tmp_path: Path) -> None:
    """A narrowed-away vendored file is `not_selected`, not `third_party`."""
    rules = ExclusionRules(selector=TargetSelector(["src"]))
    reason = rules.reason_for(
        PurePosixPath("third_party/dep.c"), real_path=None, language_supported=True
    )
    assert reason is ExclusionReason.NOT_SELECTED


def test_a_file_above_the_size_cap_is_excluded_as_too_large(tmp_path: Path) -> None:
    root = write_tree(tmp_path, {"src/big.c": "void big(void){}\n" + "// pad\n" * 200})
    database = write_compdb(root, [compdb_entry(root, str(root / "src/big.c"))])
    config = intake_config()
    small = config.model_copy(
        update={"token_budget": config.token_budget.model_copy(update={"max_file_bytes": 64})}
    )
    plan = load_scan_plan(root, database, small)
    assert plan.excluded == [(PurePosixPath("src/big.c"), ExclusionReason.TOO_LARGE)]
    assert "file_too_large" in plan.limitation_kinds()
